CC=gcc
CFLAGS=-O2
CXXFLAGS=-O2

all: BOTNAME

mm-client.o: mm-client.c mm-client.h

BOTNAME.o: BOTNAME.c mm-client.h
BOTNAME: mm-client.o BOTNAME.o
	${CC} ${CFLAGS} -o $@ $^ -lm

clean:
	rm -f *.o

fresh: clean all

